### ISSUE TITLE
Upload original config.bin possible?

### ISSUE THREAD

**Issue by gargapista** [eben80/SpeedPortEntry2i#1]
This is not on issue, just a question. If i flash my router with this firmware, can I upload the config.bin into this firmware from the original? I need the voip setting, but my ISP won't give these to me, they are in the firmware/config file. 
To see clear: I'm using my own router/modem combo to connect the VDSL line, so i have internet, but since the speeport is not connected to the line, there's no voip/phone. If the config.bin would work on this firmware, the voip would work through WAN/LAN1 instead of the vdsl line.

**Comment by eben80** [comment]
Hi,
The best advice I can give you is that you are able to backup and restore user configuration using bin files. 
If this includes the VOIP settings, I'm not sure.  The firmware itself is from Cosmote and there are some Greek specific settings under the VOIP tab.

![2021-01-27 16_17_51-Speedport Entry 2i](https://user-images.githubusercontent.com/2545460/106012136-671c7080-60bb-11eb-9eb7-d0743686a243.png)

![2021-01-27 16_21_19-Speedport Entry 2i](https://user-images.githubusercontent.com/2545460/106012490-c4182680-60bb-11eb-944a-7343c088fdd3.png)

Not sure if this helps you at all.

**Comment by gargapista** [comment]
Thanks for the info and the pics. From the pictures, this may be unuseful for me, because the auth.userneme above is hard coded for the Greek address. My isp of course has another address. As far is i found out, with my isp's firmware (looks mainly default ZTE) has an interesting function. If i make a rest with the hole on the router, the voip settings will be applied from the isp server. So i made a factory reset, the voip setting are gone, and after connecting to the line they were loaded into the speedport.

**Comment by eben80** [comment]
No problem. I wasn't taking the VOIP functions into account, I just know that the firmware on my Slovak Telekom router was so locked down that I couldn't even set it's IP or disable the DHCP on it but this firmware enables a LOT more functionality. Good luck, hope you find a way to still use it.
